# Generated by Django 3.0.2 on 2020-02-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=140)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.IntegerField(choices=[(0, 'POP MUSIC'), (1, 'JAZZ'), (2, 'CLASSIC MUSIC'), (3, 'ROCK'), (4, 'HIPHOP'), (5, 'EDM'), (6, 'OTHER')], default=0)),
                ('spotify', models.URLField(blank=True)),
                ('track_no', models.PositiveIntegerField()),
                ('track_name', models.CharField(max_length=140)),
            ],
            options={
                'unique_together': {('track_no', 'track_name')},
            },
        ),
    ]
