# Generated by Django 3.0.2 on 2020-02-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.PositiveIntegerField()),
                ('track_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=140)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.IntegerField(choices=[(0, 'POP MUSIC'), (1, 'JAZZ'), (2, 'CLASSIC MUSIC'), (3, 'ROCK'), (4, 'HIPHOP'), (5, 'EDM'), (6, 'OTHER')], default=0)),
                ('spotify', models.URLField(blank=True)),
                ('tracks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Track')),
            ],
        ),
    ]
