# Generated by Django 3.0.2 on 2020-02-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.PositiveIntegerField()),
                ('track_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='album',
            name='track_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='track_no',
        ),
    ]
